version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  tokyo:
    image: tokyo:latest
    container_name: "tokyo-docproc"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`tokyo.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

# https://docs.traefik.io/user-guides/docker-compose/basic-example/